name: Generate PlantUML Diagrams
on:
  push:
    branches:
      - main
jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source 
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Generate SVG Diagrams
        uses: cloudbees/plantuml-github-action@master
        with:
            args: -v -tsvg ${{ steps.getfile.outputs.files }}
      - name: Generate SVG Diagrams
        uses: cloudbees/plantuml-github-action@master
        with:
            args: -v -tsvg "**/**.puml"
      - name: Generate PNG Diagrams
        uses: cloudbees/plantuml-github-action@master
        with:
            args: -v -tpng "**/**.puml"
      - name: Push Local Changes
        uses:  stefanzweifel/git-auto-commit-action@v4.12.0
        with: 
          commit_message: "Generate SVG and PNG images for PlantUML diagrams" 
          branch: export
