name: Generate PlantUML Diagrams
on:
  push:
    branches:
      - main
jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source 
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Generate SVG Diagrams
        uses: holowinski/plantuml-github-action@main
        with:
            args: -v -tsvg "**/**.puml" -o ${{ github.workspace }}/dist
      - name: Generate PNG Diagrams
        uses: holowinski/plantuml-github-action@main
        with:
            args: -v -tpng "**/**.puml" -o ${{ github.workspace }}/dist
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ${{ github.workspace }}/dist
          publish_branch: export